---
title: "Prevalence of analyses in the literature that are confounded by the the generic pattern among IRAP effects"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE,
                      fig.height = 3, 
                      fig.width = 6)
```

```{r}

library(tidyverse)
library(knitr)
library(kableExtra)
library(janitor)

```

# Data

List of published IRAP articles (2006-2022) taken from existing systematic review of IRAP research. 

Each article's full text was searched for examples of analyses that are potentially confounded by the generic pattern, as described in the manuscript. Text supporting each claim and the page it came from are available in the data file. 

```{r}

data_review <- read_csv("../data/review/review of confounded analyses.csv")

```

# Summarize

```{r}

data_review |>
  count(potentially_counfounded_analysis_present) |>
  mutate(percent = janitor::round_half_up(n/sum(n)*100, 1)) |>
  kable() |>
  kable_classic(full_width = FALSE)

```

